name: Latest blog post workflow
on:
    schedule:
        - cron: '0 8 */1 * *'
runs:
  using: 'node20'
  main: 'main.js'
jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                max_post_count: "3"
                feed_list: "https://www.jungley.net/rss/"
